### ISSUE TITLE
Change mongodb name?

### ISSUE THREAD

**Issue by andersla** [HASTE-project/k8s-deployments#2]
If you give a name to the mongodb like mongodb-haste then it is less likely to delete the wrong mongodb by accident?
https://github.com/HASTE-project/k8s-deployments#set-up-mongodb-with-helm

**Comment by Snapple49** [comment]
I guess. I think I left it like that since names are unique over namespaces, so we can't create a helm installation called mongodb in the labinf namespace as well for example, but better to be overly clear I guess

**Comment by Snapple49** [comment]
Updated: https://github.com/HASTE-project/k8s-deployments/commit/c9f08cfe4f9b185b21118f05b58a4996be256c57
