### ISSUE TITLE
Add ingress for RabbitMQ and mongo

### ISSUE THREAD

**Issue by Snapple49** [HASTE-project/k8s-deployments#9]
In order to avoid having to do port-forwarding all the time it might be easier to set up ingress rules, which services do you access and are these ok to be publicly accessable (over https) or should they remain closed @benblamey ?

**Comment by benblamey** [comment]
Thanks! Port 15672  for RabbitMQ would be useful!

The other one is MongoDB, which is not HTTP.

**Comment by Snapple49** [comment]
Ok, do these have authentication? Otherwise I can set that up quickly, since the ingress is public. Don't know how much harm an open RMQ could do, you can start workloads right?

**Comment by benblamey** [comment]
yea, there's auth on rabbitmq.
Ben

**Comment by Snapple49** [comment]
RabbitMQ has ingress, but the ingress won't handle non-http so mongodb will have to rely on port-forward.

**Comment by benblamey** [comment]
:thumbsup:
